from kivy.lang import Builder

Builder.load_file("./kv/namedcheckbox.kv")
Builder.load_file("./kv/sliderwithvalues.kv")
Builder.load_file("./kv/scrolledpopupcontent.kv")
Builder.load_file("./kv/namedvalueslider.kv")
Builder.load_file("./kv/custompopup.kv")
Builder.load_file("./kv/potionwidget.kv")
Builder.load_file("./kv/enchantwidget.kv")
Builder.load_file("./kv/enchantpopuplayout.kv")
Builder.load_file("./kv/attributewidget.kv")
Builder.load_file("./kv/itemslotwidget.kv")
Builder.load_file("./kv/itemtypecard.kv")
Builder.load_file("./kv/createitemscreen.kv")
Builder.load_file("./kv/createmobscreen.kv")
Builder.load_file("./kv/homescreen.kv")
Builder.load_file("./kv/itemcategoryscreen.kv")
Builder.load_file("./kv/itemtypesscreen.kv")
Builder.load_file("./kv/mobtypesscreen.kv")
Builder.load_file("./kv/mobwidget.kv")
Builder.load_file("./kv/createspawnerscreen.kv")